package com.frauas.workforce.DTO;

import com.frauas.workforce.model.Project;
import com.frauas.workforce.model.ProjectStatus;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;
import java.util.List;

/**
 * ProjectResponseDto
 *
 * Data Transfer Object for project API responses.
 * Contains complete project information including metadata fields
 * like creation/update timestamps and user information.
 *
 * Used as response body for all project-related API endpoints.
 *
 * @author Workforce Management Team
 * @version 1.0
 * @since 2025-11-16
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class ProjectResponseDto {

    /**
     * Unique identifier of the project.
     * Generated by MongoDB upon creation.
     */
    private String id;

    /**
     * Name of the project.
     */
    private String projectName;

    /**
     * Detailed description of the project.
     */
    private String projectDescription;

    /**
     * Project start date and time.
     */
    private LocalDateTime projectStart;

    /**
     * Project end date and time.
     */
    private LocalDateTime projectEnd;

    /**
     * Detailed task description.
     */
    private String taskDescription;

    /**
     * Total number of employees required for the project.
     */
    private Integer numberOfRequiredEmployees;

    /**
     * Physical or remote location of the project.
     */
    private String location;

    /**
     * List of related resource URLs.
     */
    private List<String> links;

    /**
     * List of staffing requirements with roles and skills.
     */
    private List<StaffingRequirementDto> staffingRequirements;

    /**
     * Current lifecycle status of the project.
     * Values: PLANNED, OPEN, STAFFING, ACTIVE, COMPLETED
     */
    private ProjectStatus status;

    /**
     * Publication flag indicating visibility.
     * true = visible to all employees, false = draft/hidden
     */
    private Boolean isPublished;

    /**
     * User ID of the project creator.
     */
    private String createdBy;

    /**
     * Timestamp when the project was created.
     * Automatically set by the system.
     */
    private LocalDateTime createdAt;

    /**
     * Timestamp when the project was last updated.
     * Automatically updated by the system.
     */
    private LocalDateTime updatedAt;

    /**
     * User ID of the last person who updated the project.
     */
    private String updatedBy;
}
