package com.frauas.workforce.model;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.Id;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.data.mongodb.core.mapping.Field;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;

/**
 * Project Entity
 *
 * Represents a project in the workforce management system.
 * This entity is stored in the MongoDB "projects" collection and contains
 * all information related to project management, staffing requirements,
 * and project lifecycle tracking.
 *
 * @author Workforce Management Team
 * @version 1.0
 * @since 2025-11-16
 */
@Document(collection = "projects")
@Data
@AllArgsConstructor
@EqualsAndHashCode
public class Project {

    /**
     * Unique identifier for the project.
     * Auto-generated by MongoDB.
     */
    @Id
    private String id;

    @Field("projectId")
    private String projectId;//make combination of integer and alpha

    @Field("projectDescription")
    private String projectDescription;

    @Field("projectStart")
    private LocalDate projectStart;

    @Field("projectEnd")
    private LocalDate projectEnd;

    @Field("taskDescription")
    private String taskDescription;

    @Field("requiredEmployees")
    private Integer requiredEmployees;

    @Field("links")
    private String links;

    @Field("selectedSkills")
    private List<String> selectedSkills;

    @Field("selectedLocations")
    private List<String> selectedLocations;

    @Field("roles")
    private List<RoleRequirement> roles;

    @Field("status")
    private ProjectStatus status;

    private Boolean isPublished = false;

    @Field("createdBy")
    private String createdBy;

    @CreatedDate
    private LocalDate createdAt;

    @LastModifiedDate
    private LocalDate updatedAt;

    @Field("updatedBy")
    private String updatedBy;

    public Project() {

    }

    @Data
    @AllArgsConstructor
    public static class RoleRequirement {
        private String requiredRole;
        private List<String> requiredCompetencies;
        private String capacity;
        private String numberOfEmployees;
        private String roleInput;
        private String competencyInput;
        private Boolean showRoleDropdown;
        private Boolean showCompetencyDropdown;

        public RoleRequirement() {
            this.showRoleDropdown = false;
            this.showCompetencyDropdown = false;
        }
    }
}
