package com.frauas.workforce.model;

import lombok.Data;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.Id;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.LocalDateTime;
import java.util.List;

/**
 * Project Entity
 *
 * Represents a project in the workforce management system.
 * This entity is stored in the MongoDB "projects" collection and contains
 * all information related to project management, staffing requirements,
 * and project lifecycle tracking.
 *
 * @author Workforce Management Team
 * @version 1.0
 * @since 2025-11-16
 */
@Data
@Document(collection = "projects")
public class Project {

    /**
     * Unique identifier for the project.
     * Auto-generated by MongoDB.
     */
    @Id
    private String id;

    /**
     * Name of the project.
     * Required field that provides a brief title for the project.
     */
    private String projectName;

    /**
     * Detailed description of the project.
     * Contains comprehensive information about project objectives and scope.
     */
    private String projectDescription;

    /**
     * Project start date and time.
     * Indicates when the project is scheduled to begin.
     */
    private LocalDateTime projectStart;

    /**
     * Project end date and time.
     * Indicates when the project is scheduled to be completed.
     * Must be after projectStart date.
     */
    private LocalDateTime projectEnd;

    /**
     * Detailed description of tasks to be performed.
     * Contains information about specific deliverables and work items.
     */
    private String taskDescription;

    /**
     * Total number of employees required for the project.
     * Minimum value is 1.
     */
    private Integer numberOfRequiredEmployees;

    /**
     * Physical or remote location where the project will be executed.
     * Can be office location, city, or "Remote".
     */
    private String location;

    /**
     * List of related URLs and resources.
     * May include documentation links, project management tools, repositories, etc.
     */
    private List<String> links;

    /**
     * List of specific staffing requirements for different roles.
     * Each requirement defines role, competencies, capacity, and experience level.
     */
    private List<StaffingRequirement> staffingRequirements;

    /**
     * Current status of the project.
     * Valid values: PLANNED, OPEN, STAFFING, ACTIVE, COMPLETED
     */
    private ProjectStatus status;

    /**
     * Flag indicating whether the project is published and visible to employees.
     * True = visible to all, False = draft/hidden
     */
    private Boolean isPublished;

    /**
     * ID of the user who created this project.
     * Typically a project manager or admin user.
     */
    private String createdBy;

    /**
     * Timestamp when the project was created.
     * Automatically set by Spring Data MongoDB.
     */
    @CreatedDate
    private LocalDateTime createdAt;

    /**
     * Timestamp when the project was last updated.
     * Automatically updated by Spring Data MongoDB on save.
     */
    @LastModifiedDate
    private LocalDateTime updatedAt;

    /**
     * ID of the user who last updated this project.
     * Updated manually during update operations.
     */
    private String updatedBy;

    // -------------------------------------------------------------------
    // NESTED CLASS - STAFFING REQUIREMENT
    // -------------------------------------------------------------------

    /**
     * StaffingRequirement Nested Class
     *
     * Represents specific staffing requirements for a particular role in the project.
     * Defines the skills, experience level, and time commitment needed for each role.
     */
    @Data
    public static class StaffingRequirement {

        /**
         * Job role or position title.
         * Examples: "Senior Backend Developer", "DevOps Engineer", "Project Manager"
         */
        private String role;

        /**
         * List of required technical or soft skills/competencies.
         * Examples: ["Java", "Spring Boot", "MongoDB"], ["AWS", "Docker", "Kubernetes"]
         */
        private List<String> requiredCompetencies;

        /**
         * Number of hours per week required for this role.
         * Typically ranges from part-time (10-20 hours) to full-time (40 hours).
         */
        private Integer capacityHoursPerWeek;

        /**
         * Required experience level for the role.
         * Examples: "Junior", "Mid-Level", "Senior", "Expert"
         */
        private String experienceLevel;

        /**
         * Default constructor for StaffingRequirement.
         */
        public StaffingRequirement() {}

        /**
         * Parameterized constructor for StaffingRequirement.
         *
         * @param role The job role or position title
         * @param requiredCompetencies List of required skills and competencies
         * @param capacityHoursPerWeek Number of hours per week needed
         * @param experienceLevel Required experience level (Junior/Mid-Level/Senior/Expert)
         */
        public StaffingRequirement(String role,
                                   List<String> requiredCompetencies,
                                   Integer capacityHoursPerWeek,
                                   String experienceLevel) {
            this.role = role;
            this.requiredCompetencies = requiredCompetencies;
            this.capacityHoursPerWeek = capacityHoursPerWeek;
            this.experienceLevel = experienceLevel;
        }
    }
}
