package com.frauas.workforce.model;

import lombok.AllArgsConstructor;
import lombok.Data;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.Id;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;

/**
 * Project Entity
 *
 * Represents a project in the workforce management system.
 * This entity is stored in the MongoDB "projects" collection and contains
 * all information related to project management, staffing requirements,
 * and project lifecycle tracking.
 *
 * @author Workforce Management Team
 * @version 1.0
 * @since 2025-11-16
 */
@Data
@AllArgsConstructor
@Document(collection = "projects")
public class Project {

    /**
     * Unique identifier for the project.
     * Auto-generated by MongoDB.
     */
    @Id
    private String id;

    private String projectId;

    private String projectDescription;

    private LocalDate projectStart;

    private LocalDate projectEnd;

    private String taskDescription;

    // Changed from Integer to String
    private Integer requiredEmployees;

    // Changed from List<String> to String
    private String links;

    // NEW fields
    private List<String> selectedSkills;
    private List<String> selectedLocations;

    // Updated field - now stores RoleRequirement objects
    private List<RoleRequirement> roles;

    private ProjectStatus status;

    private Boolean isPublished = false;

    private String createdBy;

    @CreatedDate
    private LocalDate createdAt;

    @LastModifiedDate
    private LocalDate updatedAt;

    private String updatedBy;

    public Project() {

    }

    @Data
    @AllArgsConstructor
    public static class RoleRequirement {
        private String requiredRole;
        private List<String> requiredCompetencies;
        private String capacity;
        private String numberOfEmployees;
        private String roleInput;
        private String competencyInput;
        private Boolean showRoleDropdown;
        private Boolean showCompetencyDropdown;

        public RoleRequirement() {
            this.showRoleDropdown = false;
            this.showCompetencyDropdown = false;
        }
    }
}
